#! /bin/sh
# /etc/init.d/xboxconfig
#
# Some things that run always
touch /var/lock/blah

# Carry out specific functions when asked to by the system
case "$1" in
  start)
    echo "Starting script xboxdrv "
    xboxdrv --trigger-as-button --id 0 --led 2 --deadzone 4000 --silent & sleep 1
    ;;
  stop)
    echo "Stopping script xboxdrv"
    /usr/bin/xboxdrv -kill
    ;;
  *)
    echo "Usage: /etc/init.d/xboxdrv {start|stop}"
    exit 1
    ;;
esac

exit 0
